### PR TITLE
removed the componentWillRecieveProps warning and reimplemented...

### PR DESCRIPTION
**Pull request by vasilevich**
updated to node-sass 5, because it didn't install.  removed and reimplemented componentWillRecieveProps with the new react API to remove the react warnings and support react 17+ later on

### CODE REVIEW

**Review by mohamedhamza12 — APPROVED** [review]

**Comment by ahummel25** [comment]
Can this be merged in? @mohamedhh @keppelen

**Comment by samgermain** [comment]
@mohamedhh  @keppelen 

I second @ahummel25

**Comment by samgermain** [comment]
@crisys11 @goldylucks @williamboman @mmahalwy @tobitos @revolunet @samuxyz @SterlingVix @adrianObel @jackfranklin @YouMinTW @jmayergit 

Could someone merge this please?

**Review by mohamedhamza12 — APPROVED** [review]

**Comment by samgermain** [comment]
@mohamedhh It looks like you approved these changes already back in Nov 2020, but it still wasn't merged. Who has write access?

**Comment by mohamedhh** [comment]
@samgermain I believe only @keppelen does unfortunately. I've given up on this change being merged in and have opted to use Facebook's regular JavaScript API

**Comment by samgermain** [comment]
@mohamedhh I tried emailing and tweeting at him, I could call his workplace. What have you tried?

**Comment by YouMinTW** [comment]
> have opted to use Facebook's regular JavaScript API
@mohamedhh @samgermain 
Me too
I also use Facebook's regular JavaScript API

**Comment by samgermain** [comment]
🥳

**Comment by liamhession** [comment]
@vasilevich and @keppelen - This was merged in in the end, but it looks like the changes were never published to npm under a new version. So i still get the warnings about `componentWillReceiveProps` and it will likely break on React 18. But to echo the above guys, probably better to just use the regular Javascript API for fb login

**Comment by andrii-shpontak** [comment]
Is there a chance that it will be added to npm in the near future?

**Pull request merged**
