### PR TITLE
Update Graph api version

### PR DESCRIPTION
**Pull request by GustavoDinizMonteiro**
Updates the default version of facebook api from 2.3 to 3.1 (latest version at this point).

NOTE: the work in progress marking is because I'm not sure if I should redo a compilation of the dist folder along with my changes, i will be grateful to anyone who can clarify this issue for me.

### CODE REVIEW

**Comment by GustavoDinizMonteiro** [comment]
Solves #241

**Comment by sbolel** [comment]
Awesome 🎉

**Comment by Mohammad-Rafi-Bhuiyan** [comment]
Greatest ❤

**Comment by Mohammad-Rafi-Bhuiyan** [comment]
Accurate 💯

**Comment by Mohammad-Rafi-Bhuiyan** [comment]
Solid💯

**Comment by Mohammad-Rafi-Bhuiyan** [comment]
Nice ❤

**Comment by Mohammad-Rafi-Bhuiyan** [comment]
Powerful 👍

**Pull request merged**
