### PR TITLE
Make it possible to override state value

### PR DESCRIPTION
**Pull request by hinderberg**

### CODE REVIEW

**Comment by keppelen** [comment]
Hi @hinderberg after resolver https://travis-ci.org/keppelen/react-facebook-login/builds/336109942#L1299 - i can merged this pr 😄

**Comment by mickelindahl** [comment]
Looking forward to be able to change the state. since facebook in Mars will enforce "Use Strict Mode for Redirect URIs". Thus state is the way to provide e.g. dynamic uri redirects (https://developers.facebook.com/docs/facebook-login/security/#surfacearea).  WIll this be merged soon?

**Comment by keppelen** [comment]
+ react-facebook-login@4.0.1

**Comment by azorath** [comment]
@patrickclover yes, see #198

**Pull request merged**
