### PR TITLE
Protect unwanted clicks 

### PR DESCRIPTION
**Pull request by goldylucks**
- Prevent clicks before FB is loaded
- Prevent multiple clicks before a response
- Reflect disabled mode with opacity

### CODE REVIEW

**Comment by goldylucks** [comment]
I think this resolves #72 
and can be a start for resolving #71

**Comment by optimatex** [comment]
@goldylucks thanks. I'll try to test it. I'm sorry for my ineptitude but could you tell me will it be enough to use npm command `npm update react-facebook-login` to use your fix ?

**Comment by keppelen** [comment]
@optimatex now you can run `npm update react-facebook-login`

**Comment by optimatex** [comment]
@goldylucks i'm sorry but i get strange problem after update. Now button is for a long time disabled until i  reload page . After page reloaded button became active again. But when i change url and render some component and then go back to signup with fb component button become in disabled

**Comment by goldylucks** [comment]
@optimatex can u provide your code and the steps to reproduce?
extra points for [gif](http://ezgif.com/video-to-gif) ;)

**Comment by optimatex** [comment]
My signin component
```
'use strict';
import React, { Component } from 'react';
import { observer } from 'mobx-react';
import FacebookLogin from 'react-facebook-login';

@observer(['profile'])
class Signin extends Component {
   render() {
      return (
         <div className="signForm__wrap">
            <div className="signForm__block">
               <form onSubmit={this.handle_submit.bind(this)} noValidate>
                     <input type="email" value={this.state.email} placeholder="Email" onChange={this.handleChange.bind(this, 'email')} />
                     <input type="password" value={this.state.password} placeholder="Password" onChange={this.handleChange.bind(this, 'password')} />
                     <button type="submit">Signin</button>
               </form>

               <FacebookLogin
                  appId="1206714152721357"
                  autoLoad={false}
                  fields="name,email,picture"
                  scope="public_profile,user_friends"
                  callback={this.handle_facebook_login.bind(this)}
                  size={'small - medium - metro'}
                  cssClass={'facebookLogin__button '}
                  textButton={'Login with Facebook'}>
               </FacebookLogin>
            </div>
         </div>
      );
   }
   constructor(props) {
      super(props);
   }
   handle_facebook_login(response) {
      this.props.profile.define_user_registration(response);
   }
}

export default Signin;
```
and in my profile controller few methods
```
define_user_registration(FB_login_response) {
      this._set_loading();
      const FB_res = FB_login_response;
      const token = FB_login_response.accessToken;
      return axios.post(`${window.ROOT_URL}/api/Account/IsRegisterd?provider=Facebook&externalAccessToken=${token}`)
      .then(FB_registered => {
         if (FB_registered.data === false) {
            this.register_external(FB_res);
         }
         else {
            this.signin_with_external(FB_res);
         }
      });
   }
   register_external(FB_login_response) {
      const info = {
         userName: FB_login_response.name,
         provider: 'Facebook',
         externalAccessToken: FB_login_response.accessToken
      };
      return axios.post(`${window.ROOT_URL}/api/account/registerexternal`, info)
      .then(response => {
         this.clearErrorMessage();
         const data = response.data;
         this._set_token(data.access_token);
         this._save_token(data.access_token);
         this._set_auth();
         // Setting user data
         this._assign_user_id(Number(data.internalUserId));
         this.set_avatar(FB_login_response.picture.data.url);
         this.set_email(FB_login_response.email);
         this.set_firstName(FB_login_response.name);
         this._save_user_data();
         this._unset_loading();
         browserHistory.push('/');
      })
   }
   signin_with_external(FB_login_response) {
      const info =  {
         params: {
            provider: 'Facebook',
            externalAccessToken: FB_login_response.accessToken
         }
      }
      return axios.get(`${window.ROOT_URL}/api/account/ObtainLocalAccessToken`, info)
      .then(response => {
         this.clearErrorMessage();
         const data = response.data;
         this._set_token(data.access_token);
         this._save_token(data.access_token);
         this._set_auth();
         // Setting user data
         this._assign_user_id(Number(data.internalUserId));
         this.set_avatar(FB_login_response.picture.data.url);
         this.set_email(FB_login_response.email);
         this.set_firstName(FB_login_response.name);
         this._save_user_data();
         this._unset_loading();
         browserHistory.push('/');
      })
      .catch(error => {
         //this.setErrorMessage(error.response.data.error_description);
      });
   }

```

Steps to reproduce: 
1) render Signin component
2) Navigate to some other url to render some other component
3) Go back to Signin component and hence render Signin again

In this procedure i got inactive button. Maybe i need something like 
```
 componentWillUnmount: function () {
            delete window['statusChangeCallback'];
            delete window['checkLoginState'];
        },
        statusChangeCallback: function(response) {
           console.log(response);
        },
        // Callback for Facebook login button
        checkLoginState: function() {
            console.log('checking login state...');
            FB.getLoginStatus(function(response) {
               statusChangeCallback(response);
            });
        },
```
i saw this in other implementation for react [here ](http://stackoverflow.com/questions/27717555/implement-facebook-api-login-with-reactjs)

**Comment by goldylucks** [comment]
@optimatex once #80 is merged and published u should b good to go :)

**Comment by optimatex** [comment]
@goldylucks now it works fine. Thanks!

**Comment by goldylucks** [comment]
@optimatex how did u get this to work?
It's not merged yet

**Comment by optimatex** [comment]
@goldylucks i don't know. I thought it was merged. So, i used npm command `update`. And it works

**Comment by alfredoreduarte** [comment]
I'm using version 3.3.3 and the button remains always semitransparent and disabled, without any error messages. I didn't change anything apart from updating. Is anybody having a similar issue?

**Comment by goldylucks** [comment]
@alfredoreduarte do u switch routes?
what r the steps to reproduce?

the routes issue was fixed and merged in #80 but @keppelen didn't publish a new version yet.

try pointing your package like this:
```javascript
// package.json
"react-facebook-login": "git://github.com/keppelen/react-facebook-login.git#b74f419625cef0df078f062b07a312e7a3330562"
```

**Comment by keppelen** [comment]
@alfredoreduarte and @goldylucks new version pusblish => https://www.npmjs.com/package/react-facebook-login

@goldylucks waiting your PR with documentation feature about css styles :)

**Pull request merged**
