### PR TITLE
Routing hot fix

### PR DESCRIPTION
**Pull request by goldylucks**
as mentioned by @optimatex here:
https://github.com/keppelen/react-facebook-login/pull/76#issuecomment-262195387

bug was introduced at #76 

The fix:
- move setFbAsyncInit and loadSdkAsynchronously to componentWillMount
- on componentWillMount, if FB sdk is loaded, skip methods and set state isSdkLoaded to `true`

### CODE REVIEW

**Comment by goldylucks** [comment]
my bad!
Moved to devDependencies :)

**Comment by keppelen** [comment]
@goldylucks remove this package in `https://github.com/keppelen/react-facebook-login/blob/master/webpack.config.dist.js` its more security because peoples not set `NODE_ENV=production`.

**Comment by goldylucks** [comment]
@keppelen in production the package won't show, regardless of people setting `NODE_ENV=production`

it's only used in the demo and in dev.

**Comment by goldylucks** [comment]
@keppelen any updates on this?
I rather make the fixes in this repo and not open another one :)

**Comment by keppelen** [comment]
@goldylucks add this new feature in README.md please?

**Comment by goldylucks** [comment]
This is not a feature man, it's a bug fix

**Comment by keppelen** [comment]
You add https://github.com/keppelen/react-facebook-login/pull/80/files#diff-437f415a64efd5e6b57b16920e7a0ffdR179 `buttonStyle` this is a new feature

**Comment by goldylucks** [comment]
yea u r right, I added that in #78 , which is closed now
this pr, #80 , was supposed to be a hotfix of the routing, on top of that.

I might add to the readme later

**Comment by keppelen** [comment]
Ok, but i not generate new version right now.

**Pull request merged**
