### PR TITLE
Added logout feature

### PR DESCRIPTION
**Pull request by marius92mc**
Also after the user logs in, the button's text is changed accordingly.

### CODE REVIEW

**Comment by SuigetsuSake** [comment]
Great feature but we should still be able to cutomize the button's text. Adding loggedInText and loggedOutText or something like this would be awesome :)

**Comment by marius92mc** [comment]
Thanks for the tip. 
I've made the required modifications and updated the PR.

**Comment by keppelen** [comment]
@marius92mc What is the meaning of a leaving Facebook button within your application?

**Comment by marius92mc** [comment]
Because at a certain point you might want to logout from your account.

**Comment by keppelen** [comment]
@marius92mc Yes, there you implement logout button in your application :)

**Comment by marius92mc** [comment]
The whole idea was to make the logout from the fb API and to change the text button, because in the previous version, after it is logged in, the text button remains the same.

**Comment by keppelen** [comment]
If you want to log out, you log out in the facebook site. This component is just to login with Facebook.

**Comment by kamyarg** [comment]
A facebook login should also permit facebook logout, facebook in their docs talks about it:

https://developers.facebook.com/docs/facebook-login/web#logout

When the user is already logged in (to your site through FB), the button text and functionality should change to logout IMHO.

**Comment by Hossman333** [comment]
@kamyarg So does that mean there is no logout functionality?

**Comment by marius92mc** [comment]
In this case should this PR be reopened by the owner and merged?

**Comment by Hossman333** [comment]
I just ended up implementing logout on my own app, but it doesnt actually logout of facebook. So I dont really know. @marius92mc

**Comment by francisrod01** [comment]
The pull request is it: https://github.com/keppelen/react-facebook-login/pull/34
So.. the doc and npm page should be updated now, 'right?
I think that that PR never was accept because `facebook.js` don't have the update.

**Comment by felippenardi** [comment]
How do I use the logout feature?

**Pull request closed without merging**
