### PR TITLE
make sure getIsMobile is a boolean value

### PR DESCRIPTION
**Pull request by tungv**
`string.match` returns either null or and array, `PropTypes.bool` will fail

### CODE REVIEW

**Comment by mihaerzen** [comment]
When will this be merged?

**Comment by tungv** [comment]
I ended up follow facebook javascript SDK guide and extract only the css rules for metro login button. No sweat and even simpler than this

**Comment by mihaerzen** [comment]
I don't think this pull request was about that. It was however fixing the issue when isMobile was not set as boolean...

**Comment by mihaerzen** [comment]
Can you maybe provide a solution how you fixed it otherwise?

**Comment by tungv** [comment]
you're right, this PR wasn't about that. I just decided to not use it any more. And you might not need it either.

**Comment by tungv** [comment]
Thank you @keppelen

**Pull request merged**
