### PR TITLE
Fix Overriding current access token error

### PR DESCRIPTION
**Pull request by jmayergit**
https://github.com/keppelen/react-facebook-login/issues/286

Simple fix for the above issue. Needs testing

### CODE REVIEW

**Comment by carlosalvarez91** [comment]
@jmayergit sorry for the newbie question but how can I update the module inside node_modules with your changes ? it looks like when I install the package, the facebook.js file inside the react-facebook-login module is already compiled into ES5

**Comment by ViktorMeduneckij** [comment]
> @jmayergit sorry for the newbie question but how can I update the module inside node_modules with your changes ? it looks like when I install the package, the facebook.js file inside the react-facebook-login module is already compiled into ES5

You either have to specify jmayergit's branch in `package.json` next to this package, so that during installation, code would be pulled from this branch or wait for this to get merged and update your package's version. Second option is, of course, better, but who knows when this will get merged. ¯\_(ツ)_/¯

**Comment by carlosalvarez91** [comment]
@ViktorMeduneckij  thanks very much, 
it looks like it will take a while to get merged, last commit was 27th december 2019

**Comment by ViktorMeduneckij** [comment]
@keppelen , could you merge this? Would really appreciate.

**Pull request merged**
