### PR TITLE
Updated peerDependencies to support React 16 without warning.

### PR DESCRIPTION
**Pull request by samuxyz**
In order to solve [#176](https://github.com/keppelen/react-facebook-login/issues/176) I changed the versioning for React in both `peerDependencies` and `devDependencies` to `15.0.0-0 || 16.0.0-0`.

Please, correct me if I'm wrong.

### CODE REVIEW

**Comment by eilinora** [comment]
Bump! This is blocking a lot of people who need to upgrade to React16 :D

**Comment by samuxyz** [comment]
@keppelen any thoughts?

**Comment by eraeser** [comment]
any plans to merge this in the near future?

**Comment by Zephir77167** [comment]
Thanks, could you please bump the version on NPM as well?

**Comment by keppelen** [comment]
@Zephir77167 new version in NPM - sorry for delay

**Comment by Zephir77167** [comment]
Thank you!

**Pull request merged**
