### PR TITLE
add style prop support

### LINKED ISSUE #74: Cannot use react style parameter
Does this component support passing in the style parameter like most react components? We use it to dynamically set our image server host from env variables.

```
<FacebookLogin
              appId={process.env.FACEBOOK_ID}
              autoLoad={false}
              textButton="Log in with Facebook"
              fields="email"
              callback={this.responseFacebook}
              version="2.7"
              cssClass="btn icon-btn btn-block space-1 signup-login-form__btn-xl btn-large btn-facebook"
              style={{backgroundImage: `url(${process.env.IMAGE_HOST}facebook-icon.svg)`}}
            />

### PR DESCRIPTION
**Pull request by goldylucks**
Changes:
- support prop buttonStyle
- support prop containerStyle
- added *sublime* to .gitignore

resolves #74

### CODE REVIEW

**Comment by keppelen** [comment]
@goldylucks you can use `cssClass` to custom css.

**Comment by goldylucks** [comment]
@keppelen how would that answer #74 ?

he needs to pass dynamic background-image

**Comment by keppelen** [comment]
@goldylucks 
```css
.btn .fa {
  /* your coding */
}
```

**Comment by goldylucks** [comment]
how can u set dynamic image in css based on ENV variable?

**Comment by mattmiddlesworth** [comment]
Thanks so much for making this change so quickly, what release will this be pushed with?

**Comment by mattmiddlesworth** [comment]
@keppelen when you use saas based css you cannot set any class with ENV variables

**Comment by keppelen** [comment]
@goldylucks @mattmiddlesworth What do you think of this?
```jsx
<FacebookLogin ..props>
 <YourComponentWithImagerOrAnyelse />
</FacebookLogin>
```

**Comment by goldylucks** [comment]
@keppelen what is the purpose of that?

**Comment by mattmiddlesworth** [comment]
Thank you for adding this, works great!

**Pull request closed without merging**
