### PR TITLE
Build two versions: one with renderProps only, and one with CSS styling.

### PR DESCRIPTION
**Pull request by jackfranklin**
This is a bit of a meaty PR but it's something we needed at work and I've made the changes we need. I thought I'd propose merging it back in in case you're interested in it.

If you're not, no worries, and we'll use our fork internally and I won't badger you with more PRs!

This PR creates two versions of the component:

- one that supports only rendering via a `render` prop
- another that parcels up the default CSS and renders the built in button styling

The default one that is imported is the one that includes styling, but a user could also `import FB from 'react-facebook-login/facebook-login-render-props'` and get a version where they have full control of the rendering. The benefit of doing this is that the bundle is around 5kb less in size because there's no CSS needed.

### CODE REVIEW

**Comment by jackfranklin** [comment]
PS: if you're not using this component so much any more or would like some help maintaining it please do give me a ping as we're using it at thread.com and would love to help :)

**Comment by keppelen** [comment]
@jackfranklin nice PR 😄

**Comment by jackfranklin** [comment]
@keppelen thank you! Would you mind publishing to npm / allowing me to do that? :)

**Comment by jackfranklin** [comment]
Also just realised I should update the README with this, I'll do that tomorrorw.

**Comment by keppelen** [comment]
@jackfranklin https://www.npmjs.com/package/react-facebook-login - version 4.0.0 :)

**Comment by jackfranklin** [comment]
🎉 thank you!

**Pull request merged**
