### PR TITLE
Support child components

### PR DESCRIPTION
**Pull request by JanuszP**
When children are provided for component, they will be used as a content of fb login button, so one can use easily UI toolkits, ie:
    <FacebookLogin
      appId="123123123"
      autoLoad
      fields="name,email,picture"
      callback={responseFacebook}
    >
      <Button>Facebook</FBButton>
    </FacebookLogin>

### CODE REVIEW

**Comment by prettymuchbryce** [comment]
@keppelen Any thoughts on this?

**Comment by keppelen** [comment]
@prettymuchbryce in next version, i thin next week.

**Comment by goncalomarques** [comment]
@keppelen when will this be merged?

**Comment by ahmetcetin** [comment]
any chance to merge this in the near future?

**Comment by keppelen** [comment]
@JanuszP you can resolve conflict and update README.md?

**Pull request merged**
